In [1]:
import pandas as pd

df = pd.read_csv("data/insurance.csv")
print("Dataset loaded. Shape:", df.shape)
df.head()

Dataset loaded. Shape: (1338, 7)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [2]:
print("Missing values per column:")
print(df.isnull().sum())

print("\nTotal missing values in dataset:", df.isnull().sum().sum())

Missing values per column:
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

Total missing values in dataset: 0

In [3]:
print("Number of duplicate rows:", df.duplicated().sum())

duplicate_rows = df[df.duplicated()]
print("\nDuplicate rows found:")
duplicate_rows

Number of duplicate rows: 1

Duplicate rows found:

     age   sex    bmi  children smoker     region    charges
581   19  male  30.59         0     no  northwest  1639.5631

In [4]:
rows_before = df.shape[0]
df = df.drop_duplicates()
rows_after = df.shape[0]

print(f"Rows before removing duplicates: {rows_before}")
print(f"Rows after removing duplicates: {rows_after}")
print(f"Duplicates removed: {rows_before - rows_after}")

Rows before removing duplicates: 1338
Rows after removing duplicates: 1337
Duplicates removed: 1

In [5]:
print("Data types of each column:")
print(df.dtypes)

Data types of each column:
age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
charges     float64
dtype: object

In [6]:
categorical_cols = df.select_dtypes(include='object').columns.tolist()
print("Categorical columns:", categorical_cols)

for col in categorical_cols:
    print(f"\n{col} -> unique values: {df[col].unique()}")

Categorical columns: ['sex', 'smoker', 'region']

sex -> unique values: <StringArray>
['female', 'male']
Length: 2, dtype: str

smoker -> unique values: <StringArray>
['yes', 'no']
Length: 2, dtype: str

region -> unique values: <StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

C:\Users\Tahira\AppData\Local\Temp\ipykernel_5004\1788877116.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns.tolist()

In [7]:
print("BEFORE preprocessing:")
print("Shape:", df.shape)
df.head()

BEFORE preprocessing:
Shape: (1337, 7)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
df['sex'] = df['sex'].map({'male': 0, 'female': 1})
df['smoker'] = df['smoker'].map({'no': 0, 'yes': 1})

print("sex and smoker encoded (0/1).")
df[['sex', 'smoker']].head()

sex and smoker encoded (0/1).

   sex  smoker
0    1       1
1    0       0
2    0       0
3    0       0
4    0       0

In [9]:
df = pd.get_dummies(df, columns=['region'], drop_first=True)

print("region one-hot encoded.")
df.head()

region one-hot encoded.

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,16884.92400,False,False,True
1,18,0,33.770,1,0,1725.55230,False,True,False
2,28,0,33.000,3,0,4449.46200,False,True,False
3,33,0,22.705,0,0,21984.47061,True,False,False
4,32,0,28.880,0,0,3866.85520,True,False,False

In [10]:
print("AFTER preprocessing:")
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nData types:")
print(df.dtypes)
df.head()

AFTER preprocessing:
Shape: (1337, 9)

Columns: ['age', 'sex', 'bmi', 'children', 'smoker', 'charges', 'region_northwest', 'region_southeast', 'region_southwest']

Data types:
age                   int64
sex                   int64
bmi                 float64
children              int64
smoker                int64
charges             float64
region_northwest       bool
region_southeast       bool
region_southwest       bool
dtype: object

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,16884.92400,False,False,True
1,18,0,33.770,1,0,1725.55230,False,True,False
2,28,0,33.000,3,0,4449.46200,False,True,False
3,33,0,22.705,0,0,21984.47061,True,False,False
4,32,0,28.880,0,0,3866.85520,True,False,False

In [11]:
print("Final missing values check:", df.isnull().sum().sum())
print("Final duplicate check:", df.duplicated().sum())
print("Final shape:", df.shape)
print("\nAll columns are now numeric:")
print(df.dtypes)

Final missing values check: 0
Final duplicate check: 0
Final shape: (1337, 9)

All columns are now numeric:
age                   int64
sex                   int64
bmi                 float64
children              int64
smoker                int64
charges             float64
region_northwest       bool
region_southeast       bool
region_southwest       bool
dtype: object

In [12]:
df.to_csv("data/insurance_cleaned.csv", index=False)
print("Cleaned dataset saved as data/insurance_cleaned.csv")

Cleaned dataset saved as data/insurance_cleaned.csv